postgres:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  user: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}

opennms:
  dbname: ${DATABASE_NAME}
  dbuser: ${DATABASE_USERNAME}
  dbpass: ${DATABASE_PASSWORD}

  timeseries:
    strategy: rrd

  rrd:
    storebyforeignsource: true
    strategyclass: org.opennms.netmgt.rrd.rrdtool.MultithreadedJniRrdStrategy

  library:
    jrrd2: /usr/lib64/libjrrd2.so