  
scope: site0core1psql
namespace: /service/
name: postgresql{{ env "NOMAD_ALLOC_INDEX" }}

#
# Docs: https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api
#
restapi:
  listen: 0.0.0.0:{{ env "NOMAD_PORT_http" }}
  connect_address: 0.0.0.0:{{ env "NOMAD_PORT_http" }}

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    #standby_cluster:
      #host: 127.0.0.1
      #port: 1111
      #primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
#      use_slots: true
      parameters:
#        wal_level: hot_standby
#        hot_standby: "on"
#        max_connections: 100
#        max_worker_processes: 8
#        wal_keep_segments: 8
#        max_wal_senders: 10
#        max_replication_slots: 10
#        max_prepared_transactions: 0
#        max_locks_per_transaction: 64
#        wal_log_hints: "on"
#        track_commit_timestamp: "off"
#        archive_mode: "on"
#        archive_timeout: 1800s
#        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: 127.0.0.1:5432
  connect_address: 127.0.0.1:5432
  data_dir: /alloc/psql
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: RANDOM_PASS
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password